### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by davidvct** [sarahmhooper/Medallion#1]
Encountered this error when execute `bash install_check.sh`. 

I am using RTX 4090.

**Comment by davidvct** [comment]
I managed to run `bash install_check.sh` without issue

What I did is install the version of `torch` and `torchvision` of 1.13.1 and 0.14.1 respectively. And modified `_get_image_size()` to `get_image_size()` in `medallion\dauphin\image_segmentation\transforms\random_affine.py`

Might need to change the version of torch and torchvision in `medallion\setup.py` before running `make dev`.

**Comment by sarahmhooper** [comment]
Thanks for the comment and fix!
